---
- name: repository.yml | Adding Ondrej Sury's PHP apt key.
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- name: repository.yml | Adding PHP PPA
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    state: present
