---
- name: php-modules.yml | Installing PHP Modules
  apt:
    name: "{{ php_modules_install }}"
    update_cache: true
    autoremove: true
    autoclean: true
    install-recommends: false
    state: present
