---
- name: security.yml | Configuring security.conf
  template:
    src: security.conf.j2
    dest: /etc/nginx/conf.d/security.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
